// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SimTrainer.Api.Infrastructure;

#nullable disable

namespace SimTrainer.Api.Infrastructure.Migrations;

[DbContext(typeof(SimTrainerDbContext))]
partial class SimTrainerDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.CompressionEvent", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
            b.Property<decimal>("DepthCm").HasPrecision(4, 2).HasColumnType("decimal(4,2)");
            b.Property<bool>("FullRecoil").HasColumnType("bit");
            b.Property<decimal>("QualityScore").HasPrecision(5, 1).HasColumnType("decimal(5,1)");
            b.Property<int>("RateBpm").HasColumnType("int");
            b.Property<Guid>("SessionId").HasColumnType("uniqueidentifier");
            b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("SessionId");
            b.ToTable("CompressionEvents");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.Learner", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Role").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.HasKey("Id");
            b.ToTable("Learners");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.ScenarioChange", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
            b.Property<string>("PreviousScenario").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("ScenarioName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<Guid>("SessionId").HasColumnType("uniqueidentifier");
            b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("SessionId");
            b.ToTable("ScenarioChanges");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.TrainingSession", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<DateTime?>("EndedAt").HasColumnType("datetime2");
            b.Property<Guid>("LearnerId").HasColumnType("uniqueidentifier");
            b.Property<decimal?>("OverallScore").HasPrecision(5, 1).HasColumnType("decimal(5,1)");
            b.Property<string>("SessionType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("StartedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("LearnerId");
            b.ToTable("TrainingSessions");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.VitalSnapshot", b =>
        {
            b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));
            b.Property<int>("DiastolicBp").HasColumnType("int");
            b.Property<int>("HeartRate").HasColumnType("int");
            b.Property<int>("RespiratoryRate").HasColumnType("int");
            b.Property<Guid>("SessionId").HasColumnType("uniqueidentifier");
            b.Property<int>("SpO2").HasColumnType("int");
            b.Property<int>("SystolicBp").HasColumnType("int");
            b.Property<DateTime>("Timestamp").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("SessionId");
            b.ToTable("VitalSnapshots");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.CompressionEvent", b =>
        {
            b.HasOne("SimTrainer.Api.Domain.Entities.TrainingSession", "Session")
                .WithMany("Compressions")
                .HasForeignKey("SessionId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Session");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.ScenarioChange", b =>
        {
            b.HasOne("SimTrainer.Api.Domain.Entities.TrainingSession", "Session")
                .WithMany("ScenarioChanges")
                .HasForeignKey("SessionId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Session");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.TrainingSession", b =>
        {
            b.HasOne("SimTrainer.Api.Domain.Entities.Learner", "Learner")
                .WithMany("Sessions")
                .HasForeignKey("LearnerId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Learner");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.VitalSnapshot", b =>
        {
            b.HasOne("SimTrainer.Api.Domain.Entities.TrainingSession", "Session")
                .WithMany("Vitals")
                .HasForeignKey("SessionId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Session");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.Learner", b =>
        {
            b.Navigation("Sessions");
        });

        modelBuilder.Entity("SimTrainer.Api.Domain.Entities.TrainingSession", b =>
        {
            b.Navigation("Compressions");
            b.Navigation("ScenarioChanges");
            b.Navigation("Vitals");
        });
    }
}
